DROP TABLE IF EXISTS `rigs`;

CREATE TABLE `rigs` (
  `id` int(11)  AUTO_INCREMENT PRIMARY KEY,
  `defunct` int(12) ,
  `off` int(12) ,
  `allowed` int(12) ,
  `overheat` int(12) ,
  `pool_info` varchar(256) ,
  `pool` varchar(256) ,
  `miner_version` varchar(64) ,
  `rx_kbps` int(11) ,
  `tx_kbps` int(11) ,
  `kernel` varchar(64) ,
  `boot_mode` varchar(64) ,
  `uptime` int(11) ,
  `check_in_time` int(13) ,
  `human_uptime` varchar(64) ,
  `mac` varchar(64) ,
  `hostname` varchar(64) ,
  `rack_loc` varchar(64) ,
  `ip` varchar(64) ,
  `mobo` varchar(64) ,
  `lan_chip` varchar(128) ,
  `load` int(11) ,
  `ram` int(11) ,
  `cpu_temp` int(11) ,
  `cpu_name` varchar(128) ,
  `rofs` int(11) ,
  `drive_name` varchar(64) ,
  `freespace` decimal(3,1) ,
  `temp` varchar(64) ,
  `version` varchar(32) ,
  `miner_secs` int(11) ,
  `adl_error` varchar(64) DEFAULT NULL,
  `proxy_problem` varchar(64) ,
  `updating` int(12) ,
  `connected_displays` varchar(64) DEFAULT NULL,
  `resolution` varchar(64) DEFAULT NULL,
  `gethelp` varchar(64) DEFAULT NULL,
  `config_error` varchar(64) DEFAULT NULL,
  `send_remote` varchar(64) ,
  `autorebooted` int(12) ,
  `status` varchar(64) ,
  `driver` varchar(64) ,
  `selected_gpus` varchar(64) DEFAULT NULL,
  `gpus` int(11) ,
  `fanrpm` varchar(64) ,
  `fanpercent` varchar(64) ,
  `hash` decimal(6,2) ,
  `miner` varchar(64) ,
  `miner_hashes` varchar(64) ,
  `models` varchar(512) ,
  `bioses` varchar(256) ,
  `default_core` varchar(64) ,
  `default_mem` varchar(64) ,
  `vramsize` varchar(64) ,
  `core` varchar(64) ,
  `mem` varchar(64) ,
  `memstates` varchar(64) ,
  `meminfo` varchar(512) ,
  `voltage` varchar(64) ,
  `overheatedgpu` varchar(64) DEFAULT NULL,
  `throttled` varchar(64) DEFAULT NULL,
  `powertune` varchar(64),
  `timestamp` varchar(64)
) ;

